version: "3.2"

services:
  firefox-syncserver:
    image: crazymax/firefox-syncserver:latest
    container_name: firefox_syncserver
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    volumes:
      - "firefox-syncserver:/data"
    env_file:
      - "./firefox-syncserver.env"
    restart: always

volumes:
  firefox-syncserver:
