version: '3.2'

services:
  traefik:
    image: traefik:1.6-alpine
    command:
      - --logLevel=INFO
      - --defaultentrypoints=http,https
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --docker
      - --docker.exposedbydefault=false
      - --docker.domain=example.com
      - --acme=true
      - --acme.acmelogging=true
      - --acme.email=webmaster@example.com
      - --acme.storage=acme.json
      - --acme.entryPoint=https
      - --acme.onhostrule=true
      - --acme.httpchallenge=true
      - --acme.httpchallenge.entrypoint=http
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  firefox-syncserver:
    image: crazymax/firefox-syncserver:latest
    container_name: firefox-syncserver
    volumes:
      - firefox-syncserver:/data
    labels:
      - traefik.enable=true
      - traefik.backend=firefox-syncserver
      - traefik.port=5000
      - traefik.frontend.rule=Host:firefox-syncserver.example.com
    environment:
      - TZ=Europe/Paris
      - FF_SYNCSERVER_PUBLIC_URL=https://firefox-syncserver.example.com
      - FF_SYNCSERVER_SECRET=5up3rS3kr1t
      - FF_SYNCSERVER_ALLOW_NEW_USERS=true
      - FF_SYNCSERVER_FORCE_WSGI_ENVIRON=false
    restart: always

volumes:
  firefox-syncserver:
